name: ci-stable-release

on:
  push:
    branches: [regctl]
    paths:
      - "!STABLE-RELEASE"
    #  - ".github/workflows/ci-stable-release.yml"

jobs:
  push-stable-version:
    name: Create KubeArmor stable release
    # if: github.repository == 'kubearmor/kubearmor'
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18
      
      - name: Install regctl
        uses: iarekylew00t/regctl-installer@v1

      - name: Check install
        run: regctl version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Generate the stable version of KubeArmor in Docker Hub
        run: |
          regctl image copy zhy76/kubearmor:latest zhy76/kubearmor:stable
